
name: Hexo Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-lastest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Deploy
        run: |
          hexo clean
          hexo g
          hexo d