name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 你的默认分支

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Setup Hexo
      env: 
        ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "447721326@qq.com"
        git config --global user.name "talentstream"
        npm install hexo-cli -g
        npm install

    - name: Deploy
      run: |
        hexo clean
        hexo g
        hexo d
